version: '3'

services:
  stellar:
    image: 'stellar/quickstart:latest'
    command: --standalone
    volumes:
      - './volumes:/opt/stellar'
    environment:
      POSTGRES_PASSWORD: samplepass
    ports:
     - 5432:5432
     - 8000:8000
     - 11625:11625
     - 11626:11626
     
